### ISSUE TITLE
Constrain SHOW command output

### ISSUE THREAD

**Issue by diethardsteiner** [rpbouman/pash#5]
With the SHOW command it would be good to additionally/optionally constrain on something, e.g.:

```
SHOW MEMBERS [SteelWheelsSales].[Product].[Line];
```

This applies to `PROPERTIES` and several other ones as well.

Thanks!

**Comment by rpbouman** [comment]
This is a good suggestion!

This is already supported, but not quite in the way you propose. 

SHOW is designed as a wrapper around XML/A DISCOVER requests. These requests allow a so-called restrictions list which can be used to convey conditions to filte the output.

To see which restrictions are available, do:

HELP SHOW <object>

For example to see which restrictions are supported for MEMBERS, do

HELP SHOW MEMBERS

And you'll get a table with name, data type, description of each column in the SHOW resultset. There's also a Restriction column, which tells you Yes/No whether that column can be used as restriction. 

From this output you might notice that CUBE_NAME and LEVEL_UNIQUE_NAME is supported as restriction, so you can type:

SHOW MEMBERS 
WHERE CUBE_NAME = 'SteelWheelsSales' 
AND      LEVEL_UNIQUE_NAME = '[Product].[Line]';

(Of course since the steelwheels schema only has one cube you could also omit the CUBE_NAME restriction and simply type:

SHOW MEMBERS 
WHERE LEVEL_UNIQUE_NAME = '[Product].[Line]';

)

I hope this helps. Closing this issue for now. feel free to re-open if you have more suggestions to improve this feature.

**Comment by diethardsteiner** [comment]
Ok, excellent, thanks a lot!
